/*
 * Copyright (c) 2006-2021, RT-Thread Development Team
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Change Logs:
 * Date           Author       Notes
 * 2022-10-24     myshow       the first version
 */
#include <rtthread.h>

#include "fffeFrame.h"

#define DBG_TAG "fffe  "
#define DBG_LVL DBG_INFO
#include <rtdbg.h>

/*
 * This table was generated by the following program.
   #include <stdio.h>
   int
   main ()
   {
     unsigned int i, j;
     unsigned int c;
     int table[256];
     for (i = 0; i < 256; i++)
       {
     for (c = i << 24, j = 8; j > 0; --j)
       c = c & 0x80000000 ? (c << 1) ^ 0x04c11db7 : (c << 1);
     table[i] = c;
       }
     printf ("static const unsigned int crc32_table[] =\n{\n");
     for (i = 0; i < 256; i += 4)
       {
     printf ("  0x%08x, 0x%08x, 0x%08x, 0x%08x",
         table[i + 0], table[i + 1], table[i + 2], table[i + 3]);
     if (i + 4 < 256)
       putchar (',');
     putchar ('\n');
       }
     printf ("};\n");
     return 0;
   }
   For more information on CRC, see, e.g.,
   http://www.ross.net/crc/download/crc_v3.txt.
 */
static const uint32_t crc32_table[] =
{
    0x00000000, 0x04c11db7, 0x09823b6e, 0x0d4326d9,
    0x130476dc, 0x17c56b6b, 0x1a864db2, 0x1e475005,
    0x2608edb8, 0x22c9f00f, 0x2f8ad6d6, 0x2b4bcb61,
    0x350c9b64, 0x31cd86d3, 0x3c8ea00a, 0x384fbdbd,
    0x4c11db70, 0x48d0c6c7, 0x4593e01e, 0x4152fda9,
    0x5f15adac, 0x5bd4b01b, 0x569796c2, 0x52568b75,
    0x6a1936c8, 0x6ed82b7f, 0x639b0da6, 0x675a1011,
    0x791d4014, 0x7ddc5da3, 0x709f7b7a, 0x745e66cd,
    0x9823b6e0, 0x9ce2ab57, 0x91a18d8e, 0x95609039,
    0x8b27c03c, 0x8fe6dd8b, 0x82a5fb52, 0x8664e6e5,
    0xbe2b5b58, 0xbaea46ef, 0xb7a96036, 0xb3687d81,
    0xad2f2d84, 0xa9ee3033, 0xa4ad16ea, 0xa06c0b5d,
    0xd4326d90, 0xd0f37027, 0xddb056fe, 0xd9714b49,
    0xc7361b4c, 0xc3f706fb, 0xceb42022, 0xca753d95,
    0xf23a8028, 0xf6fb9d9f, 0xfbb8bb46, 0xff79a6f1,
    0xe13ef6f4, 0xe5ffeb43, 0xe8bccd9a, 0xec7dd02d,
    0x34867077, 0x30476dc0, 0x3d044b19, 0x39c556ae,
    0x278206ab, 0x23431b1c, 0x2e003dc5, 0x2ac12072,
    0x128e9dcf, 0x164f8078, 0x1b0ca6a1, 0x1fcdbb16,
    0x018aeb13, 0x054bf6a4, 0x0808d07d, 0x0cc9cdca,
    0x7897ab07, 0x7c56b6b0, 0x71159069, 0x75d48dde,
    0x6b93dddb, 0x6f52c06c, 0x6211e6b5, 0x66d0fb02,
    0x5e9f46bf, 0x5a5e5b08, 0x571d7dd1, 0x53dc6066,
    0x4d9b3063, 0x495a2dd4, 0x44190b0d, 0x40d816ba,
    0xaca5c697, 0xa864db20, 0xa527fdf9, 0xa1e6e04e,
    0xbfa1b04b, 0xbb60adfc, 0xb6238b25, 0xb2e29692,
    0x8aad2b2f, 0x8e6c3698, 0x832f1041, 0x87ee0df6,
    0x99a95df3, 0x9d684044, 0x902b669d, 0x94ea7b2a,
    0xe0b41de7, 0xe4750050, 0xe9362689, 0xedf73b3e,
    0xf3b06b3b, 0xf771768c, 0xfa325055, 0xfef34de2,
    0xc6bcf05f, 0xc27dede8, 0xcf3ecb31, 0xcbffd686,
    0xd5b88683, 0xd1799b34, 0xdc3abded, 0xd8fba05a,
    0x690ce0ee, 0x6dcdfd59, 0x608edb80, 0x644fc637,
    0x7a089632, 0x7ec98b85, 0x738aad5c, 0x774bb0eb,
    0x4f040d56, 0x4bc510e1, 0x46863638, 0x42472b8f,
    0x5c007b8a, 0x58c1663d, 0x558240e4, 0x51435d53,
    0x251d3b9e, 0x21dc2629, 0x2c9f00f0, 0x285e1d47,
    0x36194d42, 0x32d850f5, 0x3f9b762c, 0x3b5a6b9b,
    0x0315d626, 0x07d4cb91, 0x0a97ed48, 0x0e56f0ff,
    0x1011a0fa, 0x14d0bd4d, 0x19939b94, 0x1d528623,
    0xf12f560e, 0xf5ee4bb9, 0xf8ad6d60, 0xfc6c70d7,
    0xe22b20d2, 0xe6ea3d65, 0xeba91bbc, 0xef68060b,
    0xd727bbb6, 0xd3e6a601, 0xdea580d8, 0xda649d6f,
    0xc423cd6a, 0xc0e2d0dd, 0xcda1f604, 0xc960ebb3,
    0xbd3e8d7e, 0xb9ff90c9, 0xb4bcb610, 0xb07daba7,
    0xae3afba2, 0xaafbe615, 0xa7b8c0cc, 0xa379dd7b,
    0x9b3660c6, 0x9ff77d71, 0x92b45ba8, 0x9675461f,
    0x8832161a, 0x8cf30bad, 0x81b02d74, 0x857130c3,
    0x5d8a9099, 0x594b8d2e, 0x5408abf7, 0x50c9b640,
    0x4e8ee645, 0x4a4ffbf2, 0x470cdd2b, 0x43cdc09c,
    0x7b827d21, 0x7f436096, 0x7200464f, 0x76c15bf8,
    0x68860bfd, 0x6c47164a, 0x61043093, 0x65c52d24,
    0x119b4be9, 0x155a565e, 0x18197087, 0x1cd86d30,
    0x029f3d35, 0x065e2082, 0x0b1d065b, 0x0fdc1bec,
    0x3793a651, 0x3352bbe6, 0x3e119d3f, 0x3ad08088,
    0x2497d08d, 0x2056cd3a, 0x2d15ebe3, 0x29d4f654,
    0xc5a92679, 0xc1683bce, 0xcc2b1d17, 0xc8ea00a0,
    0xd6ad50a5, 0xd26c4d12, 0xdf2f6bcb, 0xdbee767c,
    0xe3a1cbc1, 0xe760d676, 0xea23f0af, 0xeee2ed18,
    0xf0a5bd1d, 0xf464a0aa, 0xf9278673, 0xfde69bc4,
    0x89b8fd09, 0x8d79e0be, 0x803ac667, 0x84fbdbd0,
    0x9abc8bd5, 0x9e7d9662, 0x933eb0bb, 0x97ffad0c,
    0xafb010b1, 0xab710d06, 0xa6322bdf, 0xa2f33668,
    0xbcb4666d, 0xb8757bda, 0xb5365d03, 0xb1f740b4
};

/*
@deftypefn Extension {unsigned int} crc32 (const unsigned char *@var{buf}, @
  int @var{len}, unsigned int @var{init})
Compute the 32-bit CRC of @var{buf} which has length @var{len}.  The
starting value is @var{init}; this may be used to compute the CRC of
data split across multiple buffers by passing the return value of each
call as the @var{init} parameter of the next.
This is used by the @command{gdb} remote protocol for the @samp{qCRC}
command.  In order to get the same results as gdb for a block of data,
you must pass the first CRC parameter as @code{0xffffffff}.
This CRC can be specified as:
  Width  : 32
  Poly   : 0x04c11db7
  Init   : parameter, typically 0xffffffff
  RefIn  : false
  RefOut : false
  XorOut : 0
This differs from the "standard" CRC-32 algorithm in that the values
are not reflected, and there is no final XOR value.  These differences
make it easy to compose the values of multiple blocks.
@end deftypefn
*/
static uint32_t fffeFrame_xcrc32 (const uint8_t *buf, uint16_t len)
{
    LOG_D("  xcrc: %d", len);
    LOG_HEX("      xcrc", 16, (uint8_t *)buf, len);
    uint32_t crc = 0xffffffff;
    while (len--)
    {
        crc = (crc << 8) ^ crc32_table[((crc >> 24) ^ *buf) & 255];
        buf++;
    }
    return crc;
}

static uint16_t fffeFrame_code(uint8_t *buf, uint16_t len)
{
    LOG_D("  code: %d", len);
    LOG_HEX("      code", 16, buf, len);
    uint16_t isfind = 0;
    for (uint16_t i = 2;i < len - 2; )
    {
        if (buf[i] == 0xff)
        {
            if (isfind == 0)
            {
                rt_memmove(&buf[i + 2], &buf[i + 1], len - i - 1);
                buf[i + 1] = 0;
                isfind = i;
                len++;
                i += 2;
            }
            else if(i - isfind - 1 > 252)
            {
                rt_memmove(&buf[i + 2], &buf[i + 1], len - i - 1);
                buf[i + 1] = 0;
                isfind = i;
                len++;
                i += 2;
            }
            else
            {
                rt_memmove(&buf[i], &buf[i + 1], len - i - 1);
                buf[isfind + 1] = i - isfind - 1;
                isfind = 0;
                len--;
            }
        }
        else
        {
            i++;
        }
    }
    return len;
}

static uint16_t fffeFrame_uncode(uint8_t *buf, uint16_t len)
{
    LOG_D("uncode: %d", len);
    LOG_HEX("    uncode", 16, buf, len);
    uint16_t isfind = 0;
    for (uint16_t i = 2;i < len - 2; )
    {
        if (buf[i] == 0xff)
        {
            if (buf[i + 1] == 0)
            {
                rt_memmove(&buf[i + 1], &buf[i + 2], len - i - 1);
                len--;
                i++;
            }
            else
            {
                isfind = buf[i + 1];
                rt_memmove(&buf[i + 1], &buf[i + 2], len - i - 1);
                rt_memmove(&buf[i + isfind + 1], &buf[i + isfind], len - i - isfind - 1);
                buf[i + isfind] = 0xff;
                i += isfind + 1;
            }
        }
        else
        {
            i++;
        }
    }
    return len;
}

int16_t fffeFrame_init(fffeFrame *ff)
{
    ff->snCount = 0;
    ff->rx_len = 0;

    ff->tx_mutex = rt_mutex_create("tx_mutex", RT_IPC_FLAG_PRIO);
    if (ff->tx_mutex == RT_NULL)
    {
        LOG_E("mutex creat error!");
        return -RT_ENOMEM;
    }
    ff->rx_mutex = rt_mutex_create("rx_mutex", RT_IPC_FLAG_PRIO);
    if (ff->rx_mutex == RT_NULL)
    {
        LOG_E("mutex creat error!");
        return -RT_ENOMEM;
    }
    ff->rx_buffer = rt_malloc(ff->maxlen);
    if (ff->rx_buffer == RT_NULL)
    {
        LOG_E("buffer creat error!");
        return -RT_ENOMEM;
    }

    if (ff->init(ff) != RT_EOK)
    {
        LOG_E("init error!");
        return -RT_ERROR;
    }
    return RT_EOK;
}
RTM_EXPORT(fffeFrame_init);

int16_t fffeFrame_close(fffeFrame *ff)
{
    rt_mutex_delete(ff->tx_mutex);
    rt_mutex_delete(ff->rx_mutex);
    rt_free(ff->rx_buffer);

    if (ff->close(ff) != RT_EOK)
    {
        LOG_E("close error!");
        return -RT_ERROR;
    }
    return RT_EOK;
}
RTM_EXPORT(fffeFrame_close);

uint16_t fffeFrame_cmd(fffeFrame *ff, uint16_t cmd, const uint8_t *buffer, uint16_t size)
{
    rt_mutex_take(ff->tx_mutex, RT_WAITING_FOREVER);
    uint8_t framebuff[(size + sizeof(fffeFrameHead) + sizeof(fffeFrameEnd))*2];
    fffeFrameHead head = {
            .start = FFFEFRAME_START,
            .len = sizeof(framebuff)/2 - 4,
            .cmd = cmd,
            .sn = ff->snCount++,
    };
    rt_memcpy(framebuff, &head, sizeof(fffeFrameHead));
    rt_memcpy(&framebuff[sizeof(fffeFrameHead)], buffer, size);
    fffeFrameEnd end = {
            .check = fffeFrame_xcrc32(&framebuff[2], head.len - 4),
            .end = FFFEFRAME_END,
    };
    rt_memcpy(&framebuff[sizeof(fffeFrameHead) + size], &end, sizeof(fffeFrameEnd));

    size = fffeFrame_code(framebuff, sizeof(framebuff)/2);
    LOG_D("   cmd: %d", size);
    LOG_HEX("       cmd", 16, framebuff, size);

    if (ff->write(ff, framebuff, size) != size)
    {
        LOG_E("cmd error!");
        size = 0;
    }
    rt_mutex_release(ff->tx_mutex);
    return size;
}
RTM_EXPORT(fffeFrame_cmd);

uint16_t fffeFrame_ack(fffeFrame *ff, fffeFrame_Ack ack, uint16_t sn, uint16_t cmd, const uint8_t *buffer, uint16_t size)
{
    rt_mutex_take(ff->tx_mutex, RT_WAITING_FOREVER);
    uint8_t framebuff[(size + sizeof(fffeFrameHead) + sizeof(fffeFrameEnd))*2];
    fffeFrameHead head = {
            .start = FFFEFRAME_START,
            .len = sizeof(framebuff)/2 - 4,
            .cmd = cmd | ack,
            .sn = sn,
    };
    rt_memcpy(framebuff, &head, sizeof(fffeFrameHead));
    rt_memcpy(&framebuff[sizeof(fffeFrameHead)], buffer, size);
    fffeFrameEnd end = {
            .check = fffeFrame_xcrc32(&framebuff[2], head.len - 4),
            .end = FFFEFRAME_END,
    };
    rt_memcpy(&framebuff[sizeof(fffeFrameHead) + size], &end, sizeof(fffeFrameEnd));

    size = fffeFrame_code(framebuff, sizeof(framebuff)/2);
    LOG_D("   ack: %d", size);
    LOG_HEX("       ack", 16, framebuff, size);

    if (ff->write(ff, framebuff, size) != size)
    {
        LOG_E("ack error!");
        size = 0;
    }
    rt_mutex_release(ff->tx_mutex);
    return size;
}
RTM_EXPORT(fffeFrame_ack);

uint16_t fffeFrame_get_buffer_len(fffeFrameHead *head)
{
    return head->len + 4 - sizeof(fffeFrameHead) - sizeof(fffeFrameEnd);
}
RTM_EXPORT(fffeFrame_get_buffer_len);

int16_t fffeFrame_accept(fffeFrame *ff, uint16_t size)
{
    rt_mutex_take(ff->rx_mutex, RT_WAITING_FOREVER);
    uint16_t nblk = ((size % ff->maxlen) > 0)?(size/ff->maxlen + 1):(size/ff->maxlen);
    LOG_D("nblk  : %d %d %d", nblk, size, ff->maxlen);
    while (nblk > 0)
    {
        uint16_t nsize = 0;
        if (nblk == 1)
        {
            nsize = (size % ff->rx_len)?(size % ff->rx_len):(ff->rx_len);
        }
        else
        {
            nsize = ff->rx_len;
        }

        if (ff->rx_len + nsize > ff->maxlen)
        {
            LOG_E("Buffer size limit exceeded %d/%d", ff->rx_len + nsize, ff->maxlen);
        }
        uint16_t rx_length = ff->read(ff, ff->rx_buffer + ff->rx_len, nsize);
        if (rx_length  > 0)
        {
            LOG_D("accept: %d/%d", rx_length, nsize);
            LOG_HEX("    accept", 16, ff->rx_buffer + ff->rx_len, rx_length);
            ff->rx_len += rx_length;

            if (ff->rx_len >= sizeof(fffeFrameHead) + sizeof(fffeFrameEnd))
            {
                LOG_D("   get: %d", ff->rx_len);
                LOG_HEX("       get", 16, ff->rx_buffer, ff->rx_len);

                uint16_t mode = 0;
                uint16_t indexS = 0;
                uint16_t indexE = 0;
                uint16_t fffeLength = 0;
                for (uint16_t n = 0; n < ff->rx_len - 1; n++)
                {
                    uint16_t *pdata16 = (uint16_t *)&ff->rx_buffer[n];
                    uint16_t data16 = *pdata16;

                    fffeFrameHead *head = NULL;
                    fffeFrameEnd *end = NULL;
                    uint8_t *buffer = NULL;

                    if (data16 == FFFEFRAME_START)
                    {
                        mode = 1;
                        indexS = n;
                        n ++;
                        LOG_D("indexS: %d", indexS);
                    }
                    else if (mode == 1 && data16 == FFFEFRAME_END)
                    {
                        mode = 0;
                        indexE = n;
                        n ++;
                        LOG_D("indexE: %d", indexE);

                        fffeLength = indexE + 2 - indexS;
                        if (fffeLength >= sizeof(fffeFrameHead) + sizeof(fffeFrameEnd))
                        {
                            fffeLength = fffeFrame_uncode(&ff->rx_buffer[indexS], fffeLength);
                            LOG_D("buffer: %d", fffeLength);
                            LOG_HEX("    buffer", 16, &ff->rx_buffer[indexS], fffeLength);
                            head = (fffeFrameHead *)&ff->rx_buffer[indexS];
                            LOG_D("  head: %x %d %x %d", head->start, head->len, head->cmd, head->sn);
                            if (head->len == fffeLength - 4)
                            {
                                buffer = &ff->rx_buffer[indexS + sizeof(fffeFrameHead)];
                                end = (fffeFrameEnd *)&ff->rx_buffer[indexS + fffeLength - sizeof(fffeFrameEnd)];
                                LOG_D("   end: %x %x", end->check, end->end);
                                uint32_t crc32 = fffeFrame_xcrc32((uint8_t *)head + 2, head->len - 4);
                                if (end->check == crc32)
                                {
                                    if (head->len > ff->maxlen)
                                    {
                                        LOG_E("Please set a longer maximum length %d/%d.", head->len, ff->maxlen);
                                    }
                                    ff->rx_indicate(ff, head, buffer, end);
                                }
                                else
                                {
                                    LOG_D("   crc: error %x %x", end->check, crc32);
                                }
                            }
                            else
                            {
                                LOG_D("   len: error %d %d", head->len, fffeLength - 4);
                            }
                        }
                    }
                }
                uint16_t lessindex = ff->rx_len;
                if (indexS != 0 || indexE != 0)
                {
                    lessindex = (indexE > indexS)?(indexE + 2):(indexS);
                }
                uint16_t lessLength = ff->rx_len - lessindex;
                rt_memcpy(ff->rx_buffer, &ff->rx_buffer[lessindex], lessLength);
                ff->rx_len = lessLength;
                LOG_D("  less: %d", ff->rx_len);
                LOG_HEX("    less", 16, ff->rx_buffer, ff->rx_len);
            }
        }

        nblk -- ;
    }
    rt_mutex_release(ff->rx_mutex);

    return 0;
}
RTM_EXPORT(fffeFrame_accept);
