# RT-Thread building script for bridge

import rtconfig
from building import *

cwd     = GetCurrentDir()
path =  [cwd]
path += [cwd + '/linkLib/inc']
path += [cwd + '/app']
path += [cwd + '/support']
path += [cwd + '/support/include']
path += [cwd + '/app/code/devlib/include']
path += [cwd + '/app/code/vcp_protocol/include']
path += [cwd + '/app/code/protocol/include']

src =  Split('''
    sto_com_board.c
    linkLib/src_swos2/swos2_app.c
    linkLib/src_swos2/swos2_can.c
    linkLib/src_swos2/swos2_common.c
    linkLib/src_swos2/swos2_eth.c
    linkLib/src_swos2/swos2_file.c
    linkLib/src_swos2/swos2_gpio.c
    linkLib/src_swos2/swos2_hdlc.c
    linkLib/src_swos2/swos2_mvb.c
    linkLib/src_swos2/swos2_os.c
    linkLib/src_swos2/swos2_rs485.c
    linkLib/src_swos2/swos2_timer.c
    linkLib/src_swos2/swos2_cfg_init.c
    support/com_lib/support_libCRC.c
    support/com_lib/support_libList.c
    support/com_lib/support_libOS.c
    support/com_lib/support_libPub.c
    support/src/support_can.c
    support/src/support_eth.c
    support/src/support_filesys.c
    support/src/support_gpio.c
    support/src/support_hdlc.c
    support/src/support_init.c
    support/src/support_mvb.c
    support/src/support_rs485.c
    support/src/support_timer.c
    app/task_loop.c
    app/to_support_main.c
    app/code/app_main.c
    app/code/task/app_init.c
    app/code/task/app_led.c
    app/code/task/app_receive_data.c
    app/code/task/app_send_data.c
    app/code/vcp_protocol/vcp_app_layer.c
    app/code/vcp_protocol/vcp_app_layer_process.c
    app/code/vcp_protocol/vcp_crc.c
    app/code/vcp_protocol/vcp_safe_layer.c
    app/code/vcp_protocol/vcp_time_manage.c
    app/code/devlib/devlib_can.c
    app/code/devlib/devlib_eth.c
    app/code/devlib/devlib_hdlc.c
    app/code/devlib/devlib_mvb.c
    app/code/devlib/devlib_rs485.c
    app/code/protocol/list_manage.c
    app/code/protocol/receive_external_protocol.c
    app/code/protocol/receive_mainctl_protocol.c
    app/code/protocol/send_external_protocol.c
    app/code/protocol/send_mainctl_protocol.c
    '''
    )

group = DefineGroup('sto_com_board', src, depend = ['APP_STO_COM_BOARD'], CPPPATH = path)

Return('group')
