# RT-Thread building script for bridge

import rtconfig
from building import *

cwd     = GetCurrentDir()
path =  [cwd]
path += [cwd + '/linkLib/inc']
path += [cwd + '/app']
path += [cwd + '/support']
path += [cwd + '/support/include']

src =  Split('''
    sto_com_board.c
    linkLib/src_swos2/swos2_app.c
    linkLib/src_swos2/swos2_can.c
    linkLib/src_swos2/swos2_common.c
    linkLib/src_swos2/swos2_eth.c
    linkLib/src_swos2/swos2_file.c
    linkLib/src_swos2/swos2_gpio.c
    linkLib/src_swos2/swos2_hdlc.c
    linkLib/src_swos2/swos2_mvb.c
    linkLib/src_swos2/swos2_os.c
    linkLib/src_swos2/swos2_rs485.c
    linkLib/src_swos2/swos2_timer.c
    support/com_lib/support_libCRC.c
    support/com_lib/support_libList.c
    support/com_lib/support_libOS.c
    support/com_lib/support_libPub.c
    support/src/support_can.c
    support/src/support_eth.c
    support/src/support_filesys.c
    support/src/support_gpio.c
    support/src/support_hdlc.c
    support/src/support_init.c
    support/src/support_mvb.c
    support/src/support_rs485.c
    support/src/support_timer.c
    app/task_loop.c
    app/to_support_main.c
    '''
    )

group = DefineGroup('sto_com_board', src, depend = ['APP_STO_COM_BOARD'], CPPPATH = path)

Return('group')
