# RT-Thread building script for bridge

import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, cwd + '/inc']

src =  Split('''
    sto_com_board.c
    '''
    )

group = DefineGroup('sto_com_board', src, depend = ['APP_STO_COM_BOARD'], CPPPATH = CPPPATH)

Return('group')
