# RT-Thread building script for bridge

import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd]

src     = Split('''
                selftest.c
                gpio.c
                key.c
                filesysterm.c
                spi.c
                i2c.c
                i2s.c
                uart.c
                can.c
                eth.c
                ''')
if GetDepend(['PKG_USING_LVGL']):
    src     += Glob('gui.c');
    src     += Glob('swlogo.c');

group = DefineGroup('selftest', src, depend = ['APP_SELFTEST'], CPPPATH = CPPPATH)

Return('group')
