# RT-Thread building script for bridge

import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
                selftest.c
                """)

group = DefineGroup('selftest', src, depend = ['APP_SELFTEST'], CPPPATH = CPPPATH)

Return('group')
