# RT-Thread building script for bridge

import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd , cwd + '/gui/generated', cwd + '/gui/generated/guider_customer_fonts', cwd + '/gui/generated/guider_fonts', cwd + '/gui/custom']

src     = Split('''
                selftest.c
                gpio.c
                key.c
                filesysterm.c
                spi.c
                i2c.c
                i2s.c
                uart.c
                can.c
                eth.c
                ''')
if GetDepend(['PKG_USING_LVGL']):
    src     += Glob('gui/generated/*.c');
    src     += Glob('gui/generated/guider_fonts/*.c');
    src     += Glob('gui/generated/images/*.c');
    src     += Glob('gui/custom/*.c');

CPPDEFINES = ['LV_LVGL_H_INCLUDE_SIMPLE']

group = DefineGroup('selftest', src, depend = ['APP_SELFTEST'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
