import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = []
path = []

if not GetDepend('PKG_USING_CMSIS_5'):
    path += [cwd + '/Include']

group = DefineGroup('CMSIS-5', src, depend = [''], CPPPATH = path)

Return('group')
