# RT-Thread building script for bridge

import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
                cable_test_bench.c
                """)

group = DefineGroup('cable_test_bench', src, depend = ['APP_CABLE_TEST_BENCH'], CPPPATH = CPPPATH)

Return('group')
