# RT-Thread building script for bridge

import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, cwd + '/inc']

src =  Split('''
    sto_record_board.c
    src/led.c
    src/eth_manage.c
    src/board_info.c
    src/data_handle.c
    src/Record_Board_App.c
    src/RecordErrorCode.c
    src/file_handle_thread.c
    '''
    )

group = DefineGroup('sto_record_board', src, depend = ['APP_STO_RECORD_BOART'], CPPPATH = CPPPATH)

Return('group')
