import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()
startup_path_prefix = SDK_LIB

# add general drivers
src = Split('''
	board.c
	ports/drv_ram.c
''')

path =  [cwd]
path += [cwd + '/ports']

if GetDepend(['SOC_M4COREBOARD_NOSRAM']) or GetDepend(['SOC_M4COREBOARD_SRAM']) or GetDepend(['SOC_M4COREBOARD_SDRAM']) or GetDepend(['SOC_M4COREBOARD_VOICE']):
    if GetDepend(['SOC_M4COREBOARD_NOSRAM']):
        src += Glob('CubeMX_Config/M4_CoreBoard_NOSRAM/Src/main.c')
        src += Glob('CubeMX_Config/M4_CoreBoard_NOSRAM/Src/stm32f4xx_hal_msp.c')
        path += [cwd + '/CubeMX_Config/M4_CoreBoard_NOSRAM/Inc']
    if GetDepend(['SOC_M4COREBOARD_SRAM']):
        src += Glob('CubeMX_Config/M4_CoreBoard_SRAM/Src/main.c')
        src += Glob('CubeMX_Config/M4_CoreBoard_SRAM/Src/stm32f4xx_hal_msp.c')
        path += [cwd + '/CubeMX_Config/M4_CoreBoard_SRAM/Inc']
    if GetDepend(['SOC_M4COREBOARD_SDRAM']):
        src += Glob('CubeMX_Config/M4_CoreBoard_SDRAM/Src/main.c')
        src += Glob('CubeMX_Config/M4_CoreBoard_SDRAM/Src/stm32f4xx_hal_msp.c')
        path += [cwd + '/CubeMX_Config/M4_CoreBoard_SDRAM/Inc']
    if GetDepend(['SOC_M4COREBOARD_VOICE']):
        src += Glob('CubeMX_Config/M4_CoreBoard_VOICE/Src/main.c')
        src += Glob('CubeMX_Config/M4_CoreBoard_VOICE/Src/stm32f4xx_hal_msp.c')
        path += [cwd + '/CubeMX_Config/M4_CoreBoard_VOICE/Inc']
    CPPDEFINES = ['STM32F429xx']
    if rtconfig.PLATFORM in ['gcc']:
        src += [startup_path_prefix + '/STM32F4xx_HAL/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/startup_stm32f429xx.s']
    elif rtconfig.PLATFORM in ['armcc', 'armclang']:
        src += [startup_path_prefix + '/STM32F4xx_HAL/CMSIS/Device/ST/STM32F4xx/Source/Templates/arm/startup_stm32f429xx.s']
    elif rtconfig.PLATFORM in ['iccarm']:
        src += [startup_path_prefix + '/STM32F4xx_HAL/CMSIS/Device/ST/STM32F4xx/Source/Templates/iar/startup_stm32f429xx.s']

if GetDepend(['SOC_H7COREBOARD_NOSRAM']) or GetDepend(['SOC_H7COREBOARD_SDRAM']):
    if GetDepend(['SOC_M4COREBOARD_NOSRAM']):
        src += Glob('CubeMX_Config/H7_CoreBoard_NOSRAM/Src/main.c')
        src += Glob('CubeMX_Config/H7_CoreBoard_NOSRAM/Src/stm32h7xx_hal_msp.c')
        path += [cwd + '/CubeMX_Config/H7_CoreBoard_NOSRAM/Inc']
    if GetDepend(['SOC_H7COREBOARD_SDRAM']):
        src += Glob('CubeMX_Config/H7_CoreBoard_SDRAM/Src/main.c')
        src += Glob('CubeMX_Config/H7_CoreBoard_SDRAM/Src/stm32h7xx_hal_msp.c')
        path += [cwd + '/CubeMX_Config/H7_CoreBoard_SDRAM/Inc']
    src += Glob('drv_mpu.c')
    CPPDEFINES = ['STM32H743xx']
    if rtconfig.PLATFORM in ['gcc']:
        src += [startup_path_prefix + '/STM32H7xx_HAL/CMSIS/Device/ST/STM32H7xx/Source/Templates/gcc/startup_stm32h743xx.s']
    elif rtconfig.PLATFORM in ['armcc', 'armclang']:
        src += [startup_path_prefix + '/STM32H7xx_HAL/CMSIS/Device/ST/STM32H7xx/Source/Templates/arm/startup_stm32h743xx.s']
    elif rtconfig.PLATFORM in ['iccarm']:
        src += [startup_path_prefix + '/STM32H7xx_HAL/CMSIS/Device/ST/STM32H7xx/Source/Templates/iar/startup_stm32h743xx.s']

if GetDepend(['SOC_H7_STO_COM_1_LOARD_BOARD']) or GetDepend(['SOC_H7_STO_COM_2_LOARD_BOARD']) or GetDepend(['SOC_H7_STO_COM_CHILD_BOARD']) or GetDepend(['SOC_H7_STO_RECORD_BOARD']):
    if GetDepend(['SOC_H7_STO_COM_1_LOARD_BOARD']):
        src += Glob('CubeMX_Config/H7_STO_Com1LoardBoard/Src/main.c')
        src += Glob('CubeMX_Config/H7_STO_Com1LoardBoard/Src/stm32h7xx_hal_msp.c')
        path += [cwd + '/CubeMX_Config/H7_STO_Com1LoardBoard/Inc']
    if GetDepend(['SOC_H7_STO_COM_2_LOARD_BOARD']):
        src += Glob('CubeMX_Config/H7_STO_Com2LoardBoard/Src/main.c')
        src += Glob('CubeMX_Config/H7_STO_Com2LoardBoard/Src/stm32h7xx_hal_msp.c')
        path += [cwd + '/CubeMX_Config/H7_STO_Com2LoardBoard/Inc']
    if GetDepend(['SOC_H7_STO_COM_CHILD_BOARD']):
        src += Glob('CubeMX_Config/H7_STO_ComChildBoard/Src/main.c')
        src += Glob('CubeMX_Config/H7_STO_ComChildBoard/Src/stm32h7xx_hal_msp.c')
        path += [cwd + '/CubeMX_Config/H7_STO_ComChildBoard/Inc']
    if GetDepend(['SOC_H7_STO_RECORD_BOARD']):
        src += Glob('CubeMX_Config/H7_STO_RecordBoard/Src/main.c')
        src += Glob('CubeMX_Config/H7_STO_RecordBoard/Src/stm32h7xx_hal_msp.c')
        path += [cwd + '/CubeMX_Config/H7_STO_RecordBoard/Inc']
    src += Glob('drv_mpu.c')
    CPPDEFINES = ['STM32H743xx']
    if rtconfig.PLATFORM in ['gcc']:
        src += [startup_path_prefix + '/STM32H7xx_HAL/CMSIS/Device/ST/STM32H7xx/Source/Templates/gcc/startup_stm32h743xx.s']
    elif rtconfig.PLATFORM in ['armcc', 'armclang']:
        src += [startup_path_prefix + '/STM32H7xx_HAL/CMSIS/Device/ST/STM32H7xx/Source/Templates/arm/startup_stm32h743xx.s']
    elif rtconfig.PLATFORM in ['iccarm']:
        src += [startup_path_prefix + '/STM32H7xx_HAL/CMSIS/Device/ST/STM32H7xx/Source/Templates/iar/startup_stm32h743xx.s']
        
if GetDepend(['SOC_M4_SDP_EXTCOM_BOARD']) or GetDepend(['SOC_M4_SDP_EXCHANGE_BOARD']):
    if GetDepend(['SOC_M4_SDP_EXTCOM_BOARD']) or GetDepend(['SOC_M4_SDP_EXCHANGE_BOARD']):
        src += Glob('CubeMX_Config/M4_SDP_ExtComBoard/Src/main.c')
        src += Glob('CubeMX_Config/M4_SDP_ExtComBoard/Src/stm32f4xx_hal_msp.c')
        path += [cwd + '/CubeMX_Config/M4_SDP_ExtComBoard/Inc']
 
    CPPDEFINES = ['STM32F407xx']
    if rtconfig.PLATFORM in ['gcc']:
        src += [startup_path_prefix + '/STM32F4xx_HAL/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/startup_stm32f407xx.s']
    elif rtconfig.PLATFORM in ['armcc', 'armclang']:
        src += [startup_path_prefix + '/STM32F4xx_HAL/CMSIS/Device/ST/STM32F4xx/Source/Templates/arm/startup_stm32f407xx.s']
    elif rtconfig.PLATFORM in ['iccarm']:
        src += [startup_path_prefix + '/STM32F4xx_HAL/CMSIS/Device/ST/STM32F4xx/Source/Templates/iar/startup_stm32f407xx.s']
        
if GetDepend(['SOC_MINILINK_V2']):
    src += Glob('CubeMX_Config/stm32f103_minilink_v2/Src/main.c')
    src += Glob('CubeMX_Config/stm32f103_minilink_v2/Src/stm32f1xx_hal_msp.c')
    path += [cwd + '/CubeMX_Config/stm32f103_minilink_v2/Inc']
    CPPDEFINES = ['STM32F103xB']
    if rtconfig.PLATFORM in ['gcc']:
        src += [startup_path_prefix + '/STM32F1xx_HAL/CMSIS/Device/ST/STM32F1xx/Source/Templates/gcc/startup_stm32f103xb.s']
    elif rtconfig.PLATFORM in ['armcc', 'armclang']:
        src += [startup_path_prefix + '/STM32F1xx_HAL/CMSIS/Device/ST/STM32F1xx/Source/Templates/arm/startup_stm32f103xb.s']
    elif rtconfig.PLATFORM in ['iccarm']:
        src += [startup_path_prefix + '/STM32F1xx_HAL/CMSIS/Device/ST/STM32F1xx/Source/Templates/iar/startup_stm32f103xb.s']

if GetDepend(['SOC_ATK_EXPLORER_V24']):
    src += Glob('CubeMX_Config/stm32f407_atk_explorer_v24/Src/main.c')
    src += Glob('CubeMX_Config/stm32f407_atk_explorer_v24/Src/stm32f4xx_hal_msp.c')
    path += [cwd + '/CubeMX_Config/stm32f407_atk_explorer_v24/Inc']
    CPPDEFINES = ['STM32F407xx']
    if rtconfig.PLATFORM in ['gcc']:
        src += [startup_path_prefix + '/STM32F4xx_HAL/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/startup_stm32f407xx.s']
    elif rtconfig.PLATFORM in ['armcc', 'armclang']:
        src += [startup_path_prefix + '/STM32F4xx_HAL/CMSIS/Device/ST/STM32F4xx/Source/Templates/arm/startup_stm32f407xx.s']
    elif rtconfig.PLATFORM in ['iccarm']:
        src += [startup_path_prefix + '/STM32F4xx_HAL/CMSIS/Device/ST/STM32F4xx/Source/Templates/iar/startup_stm32f407xx.s']

if GetDepend(['RT_USING_FAL']):
    src += Glob('ports/drv_fal.c')
    src += Glob('ports/fal_init.c')
    src += Glob('ports/fal_cfg.c')
    
if GetDepend(['RT_USING_DFS']):
    src += Glob('ports/dfs_init.c')
    
if GetDepend(['RT_USING_DFS_NFS']):
    src += Glob('ports/drv_nfs.c')
    
if GetDepend(['BSP_USING_ROOTFS']):
    src += Glob('ports/drv_rootfs.c')
    
if GetDepend(['BSP_USING_FM25xx']):
    src += Glob('ports/drv_fm25xx.c')
        
if GetDepend(['BSP_USING_SPI_FLASH']):
    src += Glob('ports/drv_spiflash.c')
    
if GetDepend(['BSP_USING_S25FL512']):
    src += Glob('ports/drv_S25FL512.c')
    
if GetDepend(['BSP_USING_AT45DB321E']):
    src += Glob('ports/drv_AT45DB321E.c')
    
if GetDepend(['BSP_USING_FMC']):
    src += Glob('ports/drv_fmc.c')
    
if GetDepend(['BSP_USING_FMCLCD']):
    src += Glob('ports/drv_fmclcd.c')
    
if GetDepend(['BSP_USING_LVGL']):
    path += [cwd + '/ports/lvgl']
    src += Glob('ports/lvgl/lv_port_disp.c')
    src += Glob('ports/lvgl/lv_port_indev.c')
    src += Glob('ports/lvgl/lv_dlsyms.c')
    path += [cwd + '/ports/lvgl/demo']
    src += Glob('ports/lvgl/demo/lv_demo.c')
    src += Glob('ports/lvgl/demo/lv_demo_calendar.c')

if GetDepend(['BSP_USING_TOUCH']):
    src += Glob('ports/touch/drv_touch.c')
    if GetDepend(['TOUCH_USING_XPT2046']):
        src += Glob('ports/touch/xpt2046.c')
    if GetDepend(['TOUCH_USING_SW']):
        src += Glob('ports/touch/sw_touch.c')
    path += [cwd + '/ports/touch']
        
if GetDepend(['BSP_USING_WM8978']):
    src += Glob('ports/wm8978/drv_wm8978.c')
    src += Glob('ports/wm8978/drv_sound.c')
    path += [cwd + '/ports/wm8978']

if GetDepend(['BSP_USING_ADAU1761']):
    src += Glob('ports/adau1761/adau1761.c')
    src += Glob('ports/adau1761/drv_sound.c')
    path += [cwd + '/ports/adau1761']

if GetDepend(['BSP_USING_NORFLASH']):
    src += Glob('ports/drv_nor_flash.c')
    
if GetDepend(['BSP_USING_EMMC']):
    src += Glob('ports/drv_emmc.c')
    
if GetDepend(['BSP_USING_USBH_CHERRY']):
    src += Glob('ports/drv_usbh_cherry.c')
    
if GetDepend(['BSP_USING_USBD_CHERRY']):
    src += Glob('ports/drv_usbd_cherry.c')
    
if GetDepend(['BSP_USING_USBH_STM32']):
    src += Glob('ports/usb_stm32/drv_usbh_stm32.c')
    src += Glob('ports/usb_stm32/usb_host.c')
    src += Glob('ports/usb_stm32/usbh_conf.c')
    src += Glob('ports/usb_stm32/usbh_diskio.c')
    path += [cwd + '/ports/usb_stm32']
    
if GetDepend(['BSP_USING_KSZ8851']):
    src += Glob('ports/ksz8851/drv_fmc_eth.c')
    src += Glob('ports/ksz8851/ksz8851.c')
    if GetDepend(['BSP_USE_LINK_LAYER_COMMUNICATION']):
        src += Glob('ports/drv_link_layer_list.c')
    path += [cwd + '/ports/ksz8851']
    
if GetDepend(['BSP_USING_ETH']):
    src += Glob('ports/eth/drv_eth.c')
    
    if GetDepend(['PHY_USING_LAN8720A']):
        src += Glob('ports/eth/lan8720.c')
        
    if GetDepend(['PHY_USING_YT8522']):
    	src += Glob('ports/eth/yt8522.c')
    	
    if GetDepend(['PHY_USING_JL5104']):
    	src += Glob('ports/eth/jl5104.c')
    	
    if GetDepend(['BSP_USE_LINK_LAYER_COMMUNICATION']):
        src += Glob('ports/drv_link_layer_list.c')
    path += [cwd + '/ports/eth']
    
if GetDepend(['BSP_USING_MAX31826']):
    src += Glob('ports/drv_max31826.c')
    src += Glob('ports/drv_ds2484.c')

if GetDepend(['BSP_USING_DS28E01']):
    src += Glob('ports/drv_ds28e01.c')
        
if GetDepend(['BSP_USING_DS1682']):
    src += Glob('ports/drv_ds1682.c')
    
if GetDepend(['BSP_USING_LTC2945']):
    src += Glob('ports/drv_ltc2945.c')
    
if GetDepend(['BSP_USING_LTC2991']):
    src += Glob('ports/drv_ltc2991.c')
    
if GetDepend(['BSP_USING_DS28E01']):
    src += Glob('ports/drv_ds28e01.c')
    
if GetDepend(['BSP_USING_ICCARD_FLASH']):
    src += Glob('ports/ic_card_flash/drv_ic_card.c')
    src += Glob('ports/ic_card_flash/at45db.c')
    src += Glob('ports/ic_card_flash/s25fl512.c')

if GetDepend(['BSP_USING_I2C']):
    src += Glob('ports/drv_i2c.c')
    
if GetDepend(['BSP_USING_CPUTEMP']):
    src += Glob('ports/drv_cpu_temp.c')
    
if GetDepend(['BSP_USING_I2S']):
    src += Glob('ports/drv_i2s.c')
    
if GetDepend(['BSP_USING_EEPROM_24Cxx']):
    src += Glob('ports/drv_24cxx.c')
    
if GetDepend(['BSP_USING_LED']):
    src += Glob('ports/drv_led.c')
    
if GetDepend(['BSP_USING_TCA9555']):
    src += Glob('ports/drv_tca9555.c')
    
if GetDepend(['BSP_USING_LTC186X']):
    src += Glob('ports/drv_ltc186x.c')
    
if GetDepend(['BSP_USING_GNSS']):
    src += Glob('ports/drv_gnss.c')
    
if GetDepend(['BSP_USING_LORA']):
    src += Glob('ports/drv_lora.c')
    
if GetDepend(['BSP_USING_KSZ8794']):
    src += Glob('ports/drv_ksz8794.c')
  
if GetDepend(['BSP_USING_MCP2517FD']):
    src += Glob('ports/mcp2517/drv_mcp2517.c')
    path += [cwd + '/ports/mcp2517']
    
if GetDepend(['BSP_USING_KSZ9897']):
	src += Glob('ports/drv_ksz9897.c')
  
if GetDepend(['BSP_USING_LTC4281I']):
    src += Glob('ports/drv_ltc4281i.c')

if GetDepend(['BSP_USING_TPA626']):
	src += Glob('ports/drv_tpa626.c')
    
if GetDepend(['BSP_USING_SC16IS752']):
    src += Glob('ports/sc16is7xx/sc16is7xx.c')
    src += Glob('ports/sc16is7xx/drv_SC16IS752.c')

if GetDepend(['BSP_USING_MVB']):
    src += Glob('ports/mvb/src/drv_mvb.c')
    src += Glob('ports/mvb/src/mue_sv.c')
    src += Glob('ports/mvb/src/mue_pd_full.c')
    src += Glob('ports/mvb/src/mue_cch.c')
    src += Glob('ports/mvb/src/mue_app.c')
    src += Glob('ports/mvb/src/mue_acc.c')
    path += [cwd + '/ports/mvb/inc']
    
if GetDepend(['BSP_USING_Z8523L16']):
    src += Glob('ports/drv_z8523l16.c')

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)
Return('group')
