# RT-Thread building script for bridge

import rtconfig
from building import *

cwd     = GetCurrentDir()
path =  [cwd]

src =  Split('''
    trdp_test_public.c
    '''
    )

if GetDepend('APP_USING_TRDP_PD_CONFORMANCE_PUSH_PATTERN_TELEGRAM_TEST'):
    src += Glob('trdp_push_pattern_telegram_test.c')

if GetDepend('APP_USING_TRDP_PD_CONFORMANCE_DEST_UDP_PORT_TEST'):
    src += Glob('trdp_dest_udp_port_test.c')

if GetDepend('APP_USING_TRDP_PD_DATA_LENGTH_TEST'):
    src += Glob('trdp_data_length_test.c')

if GetDepend('APP_USING_TRDP_PD_BYTE_ALIGNMENT_TEST'):
    src += Glob('trdp_byte_alignment_test.c')

if GetDepend('APP_USING_TRDP_PD_POINT_TO_POINT_TEST'):
    src += Glob('trdp_point_to_point_test.c')

if GetDepend('APP_USING_TRDP_PD_TIMEOUT_AND_VALIDITY_TEST'):
    src += Glob('trdp_timeout_and_validity_test.c')

if GetDepend('APP_USING_TRDP_PD_TOPOLOGY_COUNTER_TEST'):
    src += Glob('trdp_topology_counter_iut_test.c')
    src += Glob('trdp_topology_counter_system_test.c')

if GetDepend('APP_USING_TRDP_PD_FCS_CHECK_TEST'):
    src += Glob('trdp_fcs_check_iut_test.c')
    src += Glob('trdp_fcs_check_system_test.c')

if GetDepend('APP_USING_TRDP_PD_PROTOCOL_VERSION_TEST'):
    src += Glob('trdp_protocol_version_iut_test.c')
    src += Glob('trdp_protocol_version_system_test.c')

    

    

group = DefineGroup('conformance_test_of_trdp', src, depend = ['APP_USING_TRDP_PD_CONFORMANCE_TEST'], CPPPATH = path)

Return('group')
