# RT-Thread building script for bridge

import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]

src =  Split("""
    led_test.c
    tax_test.c
    udisk_test.c
    key_test.c
    voice_test.c
    """
    )

group = DefineGroup('led_test', src, depend = ['APP_LY_05C1_TEST'], CPPPATH = CPPPATH)

Return('group')
